# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
from __future__ import absolute_import

import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import seer_pb2 as seer__pb2


class SeerStub(object):
  """The seer service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateStream = channel.unary_unary(
        '/seer.Seer/CreateStream',
        request_serializer=seer__pb2.CreateStreamRequest.SerializeToString,
        response_deserializer=seer__pb2.Stream.FromString,
        )
    self.GetStream = channel.unary_unary(
        '/seer.Seer/GetStream',
        request_serializer=seer__pb2.GetStreamRequest.SerializeToString,
        response_deserializer=seer__pb2.Stream.FromString,
        )
    self.UpdateStream = channel.unary_unary(
        '/seer.Seer/UpdateStream',
        request_serializer=seer__pb2.UpdateStreamRequest.SerializeToString,
        response_deserializer=seer__pb2.Stream.FromString,
        )
    self.DeleteStream = channel.unary_unary(
        '/seer.Seer/DeleteStream',
        request_serializer=seer__pb2.DeleteStreamRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ListStreams = channel.unary_unary(
        '/seer.Seer/ListStreams',
        request_serializer=seer__pb2.ListStreamsRequest.SerializeToString,
        response_deserializer=seer__pb2.ListStreamsResponse.FromString,
        )
    self.GetForecast = channel.unary_unary(
        '/seer.Seer/GetForecast',
        request_serializer=seer__pb2.GetForecastRequest.SerializeToString,
        response_deserializer=seer__pb2.Forecast.FromString,
        )
